export default {
    '/': '工作台',
    '/home/': '工作台',
    "/home/purCatalog/": "采购目录",
    "/home/outStock/": "缺样上报",
    "/home/outStock/reportdetail/": '详情',
    '/menu-center': '菜单中心',
    '/menu-center/unified': '统一菜单',
    '/menu-center/my': '我的菜单',
    '/menu-center/template': '菜单模板',
    '/menu-center/unified/details/': '详情',
    '/menu-center/unified/adjust/': '调整菜单',
    '/menu-center/my/': '我的菜单',
    '/menu-center/my/details/': '详情',
    '/menu-center/my/custom/': '自建菜单',
    '/menu-center/my/adjust/': '调整菜单',
    '/menu-center/my/choice-template/': '选择模板',
    '/menu-center/my/from-template/': '从模板新建',
    '/menu-center/template/': '菜单模板',
    '/menu-center/template/details/': '模板详情',
    '/menu-center/template/update/': '编辑模板',
    '/menu-center/template/new/': '新建模板',
    '/menu-center/public/details/': '详情',
    '/menu-center/private/': '我的菜单',
    '/menu-center/private/new/': '新增',
    '/menu-center/private/details/': '详情',
    '/menu-center/template/': '详情',
    '/menu-center/template/new/': '详情',
    '/accSupermarket/': '辅料超市',
    //采购订单
    '/pur-order': '采购订单',
    '/pur-order/list': '列表',
    '/purOrder/new/': '新建订单',
    '/pur-order/details': '详情',
    '/delivery/': '配送验收',
    '/parameter/': '台帐',
    '/parameter/purcatalog/': '采购目录',
    '/parameter/details/': '详情',
    '/setting/information/': '设置',
    '/setting/set/': '设置',
    '/setting/security/': '设置',
    '/setting/cuisine/': '设置',
    '/setting/': '设置',
    '/Setting/outStock/':'缺样上报',
    '/Setting/outStock/reportdetail/':'详情',
    '/ingredetail/':'食材详情',
    '/excipientdetail/':'辅料详情',
    '/purCatalog/': '采购目录',
    '/purCatalog/ingredetail/': '详情'
}